name: Build theme for release and deploy

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout theme
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build scripts
        run: pnpm run build:self

      - name: Build zipped files and css
        run: pnpm run zip && pnpm run build:css

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./dist/*
          makeLatest: true
          generateReleaseNotes: true

      - name: Copy readme
        run: cp README.md site/

      - name: Deploy for GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: "./site"
          enable_jekyll: true
