name: Build and release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout theme
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build scripts
        run: pnpm run build:self

      - name: Build zipped files and css
        run: pnpm run zip && pnpm run build:css

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./dist/*
          makeLatest: true
          generateReleaseNotes: true
